# Generated by Django 3.2.5 on 2021-07-20 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoIt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='nome',
            new_name='name',
        ),
    ]
