# Generated by Django 3.2.5 on 2021-07-23 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DoIt', '0002_rename_nome_list_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoIt.list'),
        ),
    ]
