# Generated by Django 3.2.5 on 2021-07-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoIt', '0004_auto_20210728_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_it_takes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='How much time it takes in minutes'),
        ),
    ]
